[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

  ```toml
[context.production.environment]
NEXT_SERVERLESS = "true"
NODE_ENV = "production"
PUSHER_APP_ID=1158825
PUSHER_APP_KEY=6eaf658ffc145d5cbb1a
PUSHER_APP_SECRET=61c56d323be0050e5a1c
PUSHER_APP_CLUSTER=us2
```